### ISSUE TITLE
Arpack and svd calls in PyCall scikitlearn conflict each other

### ISSUE THREAD

**Issue by ppalmes** [JuliaLinearAlgebra/Arpack.jl#103]
unit-testing of PCA/ICA in scikitlearn fails due to svd (fails to converge error) when Arpack is loaded but test passes without it. It seems that the svd in Arpack clashes with svd in scikitlearn.
error is: ```raise LinAlgError("SVD did not converge")```

**Comment by ppalmes** [comment]
ok, i think generally if the package has binary files, it breaks pycall. the same happens with XGBoost.jl which loads a dll file also.

**Comment by ppalmes** [comment]
fixed it by placing arpack inside function __init__()

**Comment by ViralBShah** [comment]
I believe this is not an Arpack.jl issue. Please reopen if so.
