### ISSUE TITLE
ERROR: LoadError: No deps.jl file could be found. Please try running Pkg.build(“Arpack”)

### ISSUE THREAD

**Issue by AnilSarode** [JuliaLinearAlgebra/Arpack.jl#104]
This what I am trying to plot as given in the following code 

     using DataFrames, IndexedTables, StatsPlots
     df = DataFrame(a = 1:10, b = 10 .* rand(10), c = 10 .* rand(10))
     @df df plot(:a, [:b :c], colour = [:red :blue])

In which while installing StatsPlots I got the following error `Error building 'Arpack'` which I ignore and then when I run above code I am getting the following error `ERROR: LoadError: No deps.jl file could be found. Please try running Pkg.build("Arpack")`. so use `Pkg.build("Arpack")` which gives me the following error

    ┌ Error: Error building `Arpack`: 
    │ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, 
    "Prefix(/home/anil/.julia/packages/Arpack/zCmTA/deps/usr)") is not satisfied, cannot generate 
    deps.jl!

Please help me to resolve this issue.
information about my system 

      julia> versioninfo()

     Julia Version 1.0.4
     Platform Info:
     OS: Linux (x86_64-linux-gnu)
     CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz    
     WORD_SIZE: 64
     LIBM: libopenlibm
     LLVM: libLLVM-6.0.0 (ORCJIT, haswell)

**Comment by thefonseca** [comment]
As mentioned in the [Arpack.jl README](https://github.com/JuliaLinearAlgebra/Arpack.jl), you will have to compile [arpack-ng](https://github.com/opencollab/arpack-ng) binaries.

Here is the steps I followed on macOS 10.15.4 (should also work on Linux):

1. First download the [v3.5.0 release of arpack-ng](https://github.com/opencollab/arpack-ng/releases/tag/3.5.0) and extract to a folder.

2. Install `autoconf`, `automake` and `libtool` (here is an example using Anaconda, but you could also use [Homebrew](https://brew.sh), [MacPorts](https://www.macports.org), or `apt` in Linux):
```
conda install autoconf automake libtool
```

3. Install the [gfortran compiler](http://gcc.gnu.org/wiki/GFortranBinaries).

4. Go to the folder where you extracted `arpack-ng` in step 1 and follow the [build instructions](https://github.com/opencollab/arpack-ng):
```
sh bootstrap
./configure
make
make check
make install
```

5. Copy the compiled libs to your Julia packages folder:
```
sudo cp SRC/.libs/libarpack* ~/.julia/packages/Arpack/zCmTA/deps/usr/lib/
```

6. Run `Pkg.build("Arpack")` again.

**Comment by andreasnoack** [comment]
@AnilSarode How did you install Julia? Are you using the official binaries from julialang.org?

**Comment by andreasnoack** [comment]
No rpely so closing
