### ISSUE TITLE
can't install package Junet.jl

### ISSUE THREAD

**Issue by liwen-alt** [JuliaLinearAlgebra/Arpack.jl#106]
ERROR: could not find project file in package at https://github.com/inguar/Junet.jl.git
![图片](https://user-images.githubusercontent.com/63285313/83824977-8d476780-a70a-11ea-8530-916c915c1f75.png)
![图片](https://user-images.githubusercontent.com/63285313/83824886-49ecf900-a70a-11ea-924f-b978c8d839c3.png)

**Comment by andreasnoack** [comment]
Seems unrelated to this package
