### ISSUE TITLE
Potentially switch to a 32-bit BLAS

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLinearAlgebra/Arpack.jl#113]
Now that we have a 32-bit BLAS in Yggdrasil, we could simplify our build process and link against a 32-bit BLAS. This way, we'll be using the arpack library in its intended (and perhaps better tested) way.

I wonder if anyone knows about users who use Arpack.jl with vectors/arrays that need the 64-bit ints.

**Comment by stevengj** [comment]
What would this accomplish?  Are you hitting any bugs due to the 64-bit BLAS interface?

**Comment by ViralBShah** [comment]
We've been stuck with an older release of arpack-ng: https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/76#issuecomment-560423467

You're right, it is unlikely it will fix whatever the issues are. I just wanted to mention it here to at least explore the possibility of things being more reliable in the standard configuration.

**Comment by ViralBShah** [comment]
Given that upstream `arpack-ng` supports `INTERFACE64=1`, it should be well supported.
