### ISSUE TITLE
example of a matrix-free method?

### ISSUE THREAD

**Issue by francispoulin** [JuliaLinearAlgebra/Arpack.jl#124]
I have been reading the docs and looking at the source code for this repo and wanted to say thanks to everyone for designing it.  It looks great!

One question I do have is whether someone could share an example of where `eigs` computes the eigenvalues using a matrix-free approach.

Thanks in advance for your help!

**Comment by dkarrasch** [comment]
See here: https://jutho.github.io/LinearMaps.jl/stable/

**Comment by francispoulin** [comment]
Thank you @dkarrasch , that is exactly what I was looking for!

I see that `LinearMaps` works with `Arpack.jl` but I don't see `Arnoldi.jl` or `ArnoldiMethod.jl` in the list. I presume that means that it won't work with those repos?

**Comment by dkarrasch** [comment]
It depends on how generic their interfaces are. You could give it a try and if it works, let me know (or make a little docs PR if you like).

**Comment by francispoulin** [comment]
Thanks again.  I don't know those packages yet but will check in with them to see what they suggest and maybe try using this to see if it works.  

I'm happy so will close this for now, but will post again if I find out more.

**Comment by dkarrasch** [comment]
Actually, now I do remember that I'm using LinearMaps with ArnoldiMethod somewhere, so it should work. Need to check for Arnoldi.jl.

**Comment by francispoulin** [comment]
That's encouraging.  If you find an example I'd be curious to see it, but I can also give it a try, after I learn more about that library.
