### ISSUE TITLE
Issue building Arpack. Suggests: "override this by setting ignore_platform"

### ISSUE THREAD

**Issue by hannahrocio** [JuliaLinearAlgebra/Arpack.jl#128]
Hello,

I’m hoping someone could help me with an error message I get when trying to build Arpack. It seems quite useful, but I don't actually know how to follow its suggestion. Hope someone can help me.

Error building Arpack:
│ ┌ Warning: Platform x86_64-apple-darwin14-libgfortran5 is not an officially supported platform
│ └ @ BinaryProvider /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.0.app/Contents/Resources/julia/share/julia/stdlib/v1.0/BinaryProvider/src/PlatformNames.jl:450
│ ERROR: LoadError: ArgumentError: Will not install a tarball of platform unknown-unknown-unknown on a system of platform x86_64-apple-darwin14-gcc8-cxx03 unless ignore_platform is explicitly set to true., override this by setting ignore_platform
│ Stacktrace:
│ [1] #install#143(::Prefix, ::String, ::Bool, ::Bool, ::Bool, ::Function, ::String, ::String) at /Users/vagrant/worker/juliapro-release-osx1011-0_6/build/tmp_julia/Julia-1.0.app/Contents/Resources/julia/share/julia/stdlib/v1.0/BinaryProvider/src/Prefix.jl:294
│ [2] (::getfield(BinaryProvider, Symbol("#kw##install")))(::NamedTuple{(:prefix, :force, :verbose),Tuple{Prefix,Bool,Bool}}, ::typeof(install), ::String, ::String) at ./none:0
│ [3] top-level scope at /Users/hannah/.juliapro/JuliaPro_v1.0.5-2/packages/Arpack/zCmTA/deps/build.jl:70
│ [4] include_relative(::Module, ::String) at /Applications/JuliaPro-1.0.5-2.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│ [5] include(::Module, ::String) at /Applications/JuliaPro-1.0.5-2.app/Contents/Resources/julia/Contents/Resources/julia/lib/julia/sys.dylib:?
│ [6] include(::String) at ./client.jl:392
│ [7] top-level scope at none:0
│ in expression starting at /Users/hannah/.juliapro/JuliaPro_v1.0.5-2/packages/Arpack/zCmTA/deps/build.jl:68

Thank you!

**Comment by hannahrocio** [comment]
I also posted my issue on Julia discourse: https://discourse.julialang.org/t/error-in-pkg-build-override-this-by-setting-ignore-platform/59948

**Comment by ViralBShah** [comment]
You're using a very old version of Julia I believe - v1.0. Please use the latest stable release and it should be ok.
