### ISSUE TITLE
Unexpected Pass in tests on upcoming Julia 1.7

### ISSUE THREAD

**Issue by KristofferC** [JuliaLinearAlgebra/Arpack.jl#132]
```jl
rank 2: Error During Test at /home/pkgeval/.julia/packages/Arpack/S16ni/test/runtests.jl:318
 Unexpected Pass
 Expression: (F.U)' * F.U ≈ Matrix{T}(I, nsv, nsv)
 Got correct result, please change to @test if no longer broken.
```

cc @ViralBShah, @andreasnoack

**Comment by ViralBShah** [comment]
Hmm, the comments in the tests suggest that this capability doesn't exist in Arpack.jl

https://github.com/JuliaLinearAlgebra/Arpack.jl/blob/master/test/runtests.jl#L315

**Comment by ViralBShah** [comment]
Also, I believe this doesn't happen on all platforms. So could be accidental?

**Comment by KristofferC** [comment]
Yeah, maybe. I just saw it on pkgeval.

**Comment by ViralBShah** [comment]
I saw it in the CI: https://github.com/JuliaLinearAlgebra/Arpack.jl/pull/126
