### ISSUE TITLE
rename eigs and svds?

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLinearAlgebra/Arpack.jl#14]
See https://github.com/JuliaLang/julia/issues/26832

**Comment by ViralBShah** [comment]
What do folks feel about this? Do we still want to rename?

**Comment by ViralBShah** [comment]
I feel that very little has to be gained by changing names at this stage. There are other packages that are gaining traction, and it would be best to leave the Arpack.jl API as is for now.
