### ISSUE TITLE
Type instability in eigs

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLinearAlgebra/Arpack.jl#17]
See https://github.com/JuliaLang/julia/issues/13929

**Comment by dillondaudert** [comment]
I'm doing some non-urgent work with `eigs`, I'm curious if there's any update on making it type-stable?

**Comment by andreasnoack** [comment]
Not that I'm aware of. I think it would be pretty tedious. Maybe it will be easier for https://github.com/haampie/ArnoldiMethod.jl. Maybe it already is. It's been a while since I've looked closer.

**Comment by ViralBShah** [comment]
Does this type instability affect overall applications?

**Comment by ViralBShah** [comment]
Closing as "wontfix".
