### ISSUE TITLE
Building and testing fails on Julia 1.0

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaLinearAlgebra/Arpack.jl#30]
Just wanted to get this issue to light. Dump below:

build Arpack
  Building Arpack → `~/.julia/packages/Arpack/Btbe4/deps/build.log`
┌ Error: Error building `Arpack`: 
│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(/Users/arora/.julia/packages/Arpack/Btbe4/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #write_deps_file#134(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /Users/arora/.julia/packages/BinaryProvider/ZbFxn/src/Products.jl:393
│  [3] write_deps_file(::String, ::Array{LibraryProduct,1}) at /Users/arora/.julia/packages/BinaryProvider/ZbFxn/src/Products.jl:380
│  [4] top-level scope at none:0
│  [5] include at ./boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1038
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:388
│  [9] top-level scope at none:0
│ in expression starting at /Users/arora/.julia/packages/Arpack/Btbe4/deps/build.jl:40
└ @ Pkg.Operations ~/src/julia/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068

**Comment by andreasnoack** [comment]
Most likely dup of #5. Please comment otherwise.

**Comment by GravityAssisted** [comment]
Sounds good. I will track that issue.
