### ISSUE TITLE
Build error "Could not extract the platform key"

### ISSUE THREAD

**Issue by zimmermm** [JuliaLinearAlgebra/Arpack.jl#35]
Just switched to Julia 1.0 and get the following build error:
`
Error: Error building 'Arpack': 
│ ┌ Warning: Could not extract the platform key of https://github.com/JuliaLinearAlgebra/ArpackBuilder/releases/download/v3.5.0-0.2.20/ArpackBuilder.x86_64-linux-gnu.tar.gz; continuing...
│ └ @ BinaryProvider ~/.julia/packages/BinaryProvider/UTYxu/src/Prefix.jl:224
│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(~/.julia/packages/Arpack/WP3ru/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] #write_deps_file#134(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at ~/.julia/packages/BinaryProvider/UTYxu/src/Products.jl:409
│  [2] write_deps_file(::String, ::Array{LibraryProduct,1}) at ~/.julia/packages/BinaryProvider/UTYxu/src/Products.jl:396
│  [3] top-level scope at none:0
│  [4] include(::String) at ./client.jl:388
│  [5] top-level scope at none:0
│ in expression starting at ~/.julia/packages/Arpack/WP3ru/deps/build.jl:40
`

**Comment by andreasnoack** [comment]
Dup of https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/5
