### ISSUE TITLE
Problem on JuliaPro 1.0.1.1 under Windows 

### ISSUE THREAD

**Issue by pierzy** [JuliaLinearAlgebra/Arpack.jl#47]
when trying to do 
> using Arpack
I get
[ Info: Precompiling Arpack [7d9fca2a-8960-54d3-9f78-7d1dccf2cb97]
ERROR: LoadError: No deps.jl file could be found. Please try running Pkg.build("Arpack").
...
so I try 
> Pkg.build("Arpack")
and I get
  Building Arpack → `C:\Users\alotpie89508\AppData\Local\JuliaPro1011\pkgs-1.0.1.1\packages\Arpack\U
iiMc\deps\build.log`
┌ Error: Error building `Arpack`:
│ ERROR: LoadError: UndefVarError: CompilerABI not defined
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] include at .\boot.jl:317 [inlined]
│  [3] include_relative(::Module, ::String) at .\loading.jl:1041
│  [4] include(::Module, ::String) at .\sysimg.jl:29
│  [5] include(::String) at .\client.jl:388
│  [6] top-level scope at none:0
│ in expression starting at C:\Users\alotpie89508\AppData\Local\JuliaPro1011\pkgs-1.0.1.1\packages\A
rpack\UiiMc\deps\build.jl:14
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.0.1\share\julia\stdlib\v1.0\Pkg\src\Operatio
ns.jl:1101

Any ideas? 
Thanks in advance,
Pier

**Comment by aviks** [comment]
Investigating, thanks the report and sorry for the trouble.

**Comment by andreasnoack** [comment]
This issue is unrelated to this repo so let's continue the discussion on discourse.

**Comment by pierzy** [comment]
Apparently I messed up something with the registry. After a fresh re-install of JuliaPro 1.0.1.1 Arpack built without problems.
Sorry for causing unnecessary alarm and thanks for your replies.
