### ISSUE TITLE
Building error 

### ISSUE THREAD

**Issue by phelipe** [JuliaLinearAlgebra/Arpack.jl#49]
Try to build but got error:

```(v1.0) pkg> build Arpack
  Building Arpack → `~/.julia/packages/Arpack/UiiMc/deps/build.log`
┌ Error: Error building `Arpack`: 
│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(/home/phelipe/.julia/packages/Arpack/UiiMc/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/phelipe/.julia/packages/BinaryProvider/1nGWd/src/Products.jl:408
│  [2] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at ./none:0
│  [3] top-level scope at none:0
│  [4] include(::String) at ./client.jl:388
│  [5] top-level scope at none:0
│ in expression starting at /home/phelipe/.julia/packages/Arpack/UiiMc/deps/build.jl:74
└ @ Pkg.Operations /build/julia/src/julia/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1069
```
I am using Manjaro linux:

```
julia> versioninfo()
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)

```

**Comment by andreasnoack** [comment]
Most likely a dup of #5. How did you install Julia?

**Comment by phelipe** [comment]
It was installed by oficial manjaro package manager.

**Comment by andreasnoack** [comment]
Then it is #5. In the meantime, you can work around the issue by using the official binaries from https://julialang.org/downloads/

**Comment by Kelvyn88** [comment]
Same problem here. Julia 1.0.1 in Manjaro.

**Comment by AmebaBrain** [comment]
Had same problem via package from Copr repository on Fedora 29. Removing it and installing binaries from downloads page solved the problem  

The same stated in doc

> Distribution-Specific Packages
The following distribution-specific packages are community contributed. They may not use the right versions of Julia dependencies or include important patches that the official binaries ship with. In general, bug reports will only be accepted if they are reproducible on the official generic binaries on the downloads page.

**Comment by miguelfm** [comment]
For Manjaro users, just install julia-bin package instead of julia. Pkg.build("Arpack") runs without issues using julia-bin.
