### ISSUE TITLE
eigs on a Symmetric view of sparse matrix 1000 times slower than sparse matrix alone

### ISSUE THREAD

**Issue by massimilianocomin** [JuliaLinearAlgebra/Arpack.jl#58]
Hello,

I just want to point out this strange problem, clearly seen in the benchmark below
```
using PyCall
using Arpack
using StaticArrays
using SparseArrays
using BenchmarkTools
using LinearAlgebra

function random_sparse_matrix(n)

    I = zeros(Int32,0)
    J = zeros(Int32,0)
    K = zeros(0)

    for j in 1:n
        for i in 1:j

            if i == j
                push!(I,i)
                push!(J,j)
                push!(K,rand(1)[1])

            else
                if rand(1)[1] > 0.8
                    push!(I,i)
                    push!(J,j)
                    push!(K,0.15)
                end
            end
        end
    end
    return sparse(I,J,K)
end

const x = rand(500, 500)
const A = x + x'
const B = Symmetric(A)
const C = random_sparse_matrix(500)
const D = Symmetric(C)

@btime eigs(A,nev=10,tol=1e-6)
@btime eigs(B,nev=10,tol=1e-6)
@btime eigs(C,nev=10,tol=1e-6)
@btime eigs(D,nev=10,tol=1e-6)
```

which gives the following output
```
  4.898 ms (542 allocations: 163.52 KiB)
  3.661 ms (542 allocations: 163.52 KiB)
  1.489 ms (255 allocations: 571.59 KiB)
  1.242 s (729 allocations: 170.84 KiB)
```

How can `eigs` on the **same** matrix be 1000 times slower, just because it is a Symmetric view of it ? (Shouldn't it be actually faster?)

**Comment by daviehh** [comment]
maybe due to `transpose` is ["lazy"](url
https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/index.html#Base.transpose), and `Symmetric` uses `transpose`? [code](https://github.com/JuliaLang/julia/blob/80516ca20297a67b996caa08c38786332379b6a5/stdlib/LinearAlgebra/src/symmetric.jl#L75)

**Comment by jarlebring** [comment]
I don't think this is Arpack related. Considerable effort has been put on optimizing sparse operations, and not as much for the symmetric view of sparse matrices. You can see the same issue with the matrix vector product:
```julia
julia> @btime C*x;
  16.006 μs (1 allocation: 4.06 KiB)
julia> @btime D*x;
  6.254 ms (1 allocation: 4.06 KiB)
```
The fact that the matvec corresponding to D requires half as many operations is not much comparison to the sparse operations optimizations. You could try filing the issue somewhere else (but I fear this would have low priority in Base). In any case, I suggest closing this issue?

**Comment by andreasnoack** [comment]
This should be filed in the Julia repo.
