### ISSUE TITLE
better handling of the build process: using julia built against mkl

### ISSUE THREAD

**Issue by daviehh** [JuliaLinearAlgebra/Arpack.jl#61]
Following this discussion [here](https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/5#issuecomment-451306576), one can supply a self-built arpack binary (esp. built against mkl). For this particular problem, this can be handled in a cleaner/better documented way. e.g. for `deps/build.jl`, add something like:

```
if Base.libblas_name == "libopenblas64_"
   (use openblas)
else
  (use user provided path to arpack binary, passed as argument from Pkg.build)
end
```

via manually pasting a compiled binary to `~/.julia/packages/Arpack/<pkg hash>/deps/usr/lib`, I can get `Pkg.test("Arpack")` pass on a mac using a modified script from the [binary builder script](https://github.com/JuliaLinearAlgebra/ArpackBuilder/blob/master/build_tarballs.jl), using commit `"b095052372aa95d4281a645ee1e367c28255c947"` of arpack-ng.git:

```
#!/usr/bin/env bash
source /opt/intel/mkl/bin/mklvars.sh intel64 ilp64

CMAKE_EXE_LINKER_FLAGS="${CMAKE_EXE_LINKER_FLAGS} -Wl,-rpath -Wl,$MKLROOT/lib"



# Symbols that have float32, float64, complexf32, and complexf64 support
SDCZ_SYMBOLS="axpy copy gemv geqr2 lacpy lahqr lanhs larnv lartg \
              lascl laset scal trevc trmm trsen gbmv gbtrf gbtrs \
              gttrf gttrs pttrf pttrs"
# All symbols that have float32/float64 support (including the SDCZ_SYMBOLS above)
SD_SYMBOLS="${SDCZ_SYMBOLS} dot ger labad laev2 lamch lanst lanv2 \
            lapy2 larf larfg lasr nrm2 orm2r rot steqr swap"
# All symbols that have complexf32/complexf64 support (including the SDCZ_SYMBOLS above)
CZ_SYMBOLS="${SDCZ_SYMBOLS} dotc geru unm2r"
# Add in (s|d)*_64 symbol remappings:
for sym in ${SD_SYMBOLS}; do
    SYMBOL_DEFS="${SYMBOL_DEFS} -Ds${sym}=s${sym}_64 -Dd${sym}=d${sym}_64"
done
# Add in (c|z)*_64 symbol remappings:
for sym in ${CZ_SYMBOLS}; do
    SYMBOL_DEFS="${SYMBOL_DEFS} -Dc${sym}=c${sym}_64 -Dz${sym}=z${sym}_64"
done
# Add one-off symbol mappings; things that don't fit into any other bucket:
for sym in scnrm2 dznrm2 csscal zdscal dgetrf dgetrs; do
    SYMBOL_DEFS="${SYMBOL_DEFS} -D${sym}=${sym}_64"
done
# Set up not only lowercase symbol remappings, but uppercase as well:
SYMBOL_DEFS="${SYMBOL_DEFS} ${SYMBOL_DEFS^^}"

FFLAGS="${FFLAGS} -fdefault-integer-8 ${SYMBOL_DEFS} -ff2c"

cmake ..  -DINTERFACE64=1 -DBUILD_SHARED_LIBS=ON -DBLAS_LIBRARIES="-L$MKLROOT/lib -lmkl_rt" -DLAPACK_LIBRARIES="-L$MKLROOT/lib -lmkl_rt" -DCMAKE_EXE_LINKER_FLAGS="${CMAKE_EXE_LINKER_FLAGS}" -DCMAKE_Fortran_FLAGS="${FFLAGS}"
```

Additional question: if Pkg.test("Arpack") pass, is it safe to assume that the self-built binary is compatible? Thanks!

**Comment by daviehh** [comment]
note: changes to the script:
- set env variable to set mkl path via `source /opt/intel/mkl/bin/mklvars.sh intel64 ilp64`
- `CMAKE_EXE_LINKER_FLAGS`: added `-Wl,$MKLROOT/lib`
- `FFLAGS` added `-ff2c` as per [here](https://github.com/JuliaLang/julia/issues/17946)
- `cmake ..  -DINTERFACE64=1 -DBUILD_SHARED_LIBS=ON -DBLAS_LIBRARIES="-L$MKLROOT/lib -lmkl_rt" -DLAPACK_LIBRARIES="-L$MKLROOT/lib -lmkl_rt" -DCMAKE_EXE_LINKER_FLAGS="${CMAKE_EXE_LINKER_FLAGS}" -DCMAKE_Fortran_FLAGS="${FFLAGS}"`

**Comment by andreasnoack** [comment]
Dup of #7
