### ISSUE TITLE
Use Arpack.jl with MKL

### ISSUE THREAD

**Issue by joaquimg** [JuliaLinearAlgebra/Arpack.jl#62]
I have julia 0.6 code which I ran with Arpack's eig function with MKL by using a JuliaPro distribution.
I would like to use Arpack.jl with MKL, what is the best/easiest way to do that?
Are there plans to include MKL support here?
I just saw some people building julia with MKL on their own and trying to link in #7 and #61

**Comment by andreasnoack** [comment]
This is tracked in #7
