### ISSUE TITLE
julia-conda based: Error: Error building `Arpack`

### ISSUE THREAD

**Issue by cailiangliang765** [JuliaLinearAlgebra/Arpack.jl#66]
julia> Pkg.build("Arpack")
  Building Arpack → `~/.julia/packages/Arpack/CH7vk/deps/build.log`
┌ Error: Error building `Arpack`: 
│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(/home/cllcentosvm/.julia/packages/Arpack/CH7vk/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/cllcentosvm/.julia/packages/BinaryProvider/4F5Hq/src/Products.jl:414
│  [3] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at ./none:0
│  [4] top-level scope at none:0
│  [5] include at ./boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1044
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:392
│  [9] top-level scope at none:0
│ in expression starting at /home/cllcentosvm/.julia/packages/Arpack/CH7vk/deps/build.jl:74
└ @ Pkg.Operations /home/conda/feedstock_root/build_artifacts/julia_1548684429855/work/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097

julia> versioninfo()
Julia Version 1.0.3
Platform Info:
  OS: Linux (x86_64-conda_cos6-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)

julia>

**Comment by andreasnoack** [comment]
How did you install Julia?

**Comment by cailiangliang765** [comment]
> How did you install Julia?

`conda install -c conda-forge julia`
in https://anaconda.org/conda-forge/julia.

**Comment by andreasnoack** [comment]
Please try if you can reproduce with the official binaries from https://julialang.org/downloads/

**Comment by cailiangliang765** [comment]
> Please try if you can reproduce with the official binaries from https://julialang.org/downloads/
I try this solution from #5 , it can solve my build perfectly. @andreasnoack 
https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/5#issuecomment-457172134
