### ISSUE TITLE
Error building Arpack

### ISSUE THREAD

**Issue by sparrowcat** [JuliaLinearAlgebra/Arpack.jl#67]
I get an error when trying to build Arpack:  <br>
Building Arpack → `~/.julia/packages/Arpack/UiiMc/deps/build.log`
┌ Error: Error building `Arpack`: 
│ [ Info: Downloading https://github.com/JuliaLinearAlgebra/ArpackBuilder/releases/download/v3.5.0-3/Arpack.v3.5.0-3.x86_64-linux-gnu-gcc8.tar.gz to /home/seknappe/.julia/packages/Arpack/UiiMc/deps/usr/downloads/Arpack.v3.5.0-3.x86_64-linux-gnu-gcc8.tar.gz...
│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(/home/seknappe/.julia/packages/Arpack/UiiMc/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/seknappe/.julia/packages/BinaryProvider/TcAwt/src/Products.jl:414
│  [2] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at ./none:0
│  [3] top-level scope at none:0
│  [4] include(::String) at ./client.jl:403
│  [5] top-level scope at none:0
│ in expression starting at /home/seknappe/.julia/packages/Arpack/UiiMc/deps/build.jl:74
[16:35:30] ######################################################################## 100.0% 
└ @ Pkg.Operations /build/julia/src/julia-1.1.0/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075
<br>
I've tried doing `dev Arpack` as well but I get the same error (with a different path to the file) <br>
I installed julia using `pacman -S julia` and the arch linux website says that that julia package is from the official binaries.

**Comment by HuangXi1987** [comment]
Just copy the system lib in /usr/lib and overwrite libarpack.so.2.0.0 can fix this.
My case:
```bash
cp /usr/lib/libarpack.so.2.1.0 ~/.julia/packages/Arpack/cu5By/deps/usr/lib/libarpack.so.2.0.0
```

**Comment by luizsol** [comment]
I'm having the same problem. Already tried the @HuangXi1987 proposed solution but it didn't work.

I'm using the official Julia 1.1.1 binaries in a Manjaro distro.

**Comment by HuangXi1987** [comment]
Maybe you shoud re-run `import Pkg;Pkg.build("Arpack")` before doing other real computing task.

**Comment by claudefalbriard** [comment]
Getting the error on a binary distributed version under Ubuntu Linux (conda julia 1.0.3) unable to build "Arpack" receiving the following error message. 

Error: Error building `Arpack`: 
`│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(/home/claude/.julia/packages/Arpack/cu5By/deps/usr)") is not satisfied, cannot generate deps.jl!`

I've installed the Openblas libraries with command "sudo apt-get install libopenblas-dev"
Any hint how to solve this build to add Julia linear algebra support? 

My environment is: 
```
julia> versioninfo()
Julia Version 1.0.3
Platform Info:
  OS: Linux (x86_64-conda_cos6-linux-gnu)
  CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by Paethon** [comment]
> Just copy the system lib in /usr/lib and overwrite libarpack.so.2.0.0 can fix this.
> My case:
> 
> ```shell
> cp /usr/lib/libarpack.so.2.1.0 ~/.julia/packages/Arpack/cu5By/deps/usr/lib/libarpack.so.2.0.0
> ```

Thanks, that solves the Problem

**Comment by andreasnoack** [comment]
Closing as dup of #5
