### ISSUE TITLE
Bypass BinaryProvider for already present libarpack.so

### ISSUE THREAD

**Issue by JKrehl** [JuliaLinearAlgebra/Arpack.jl#71]
Numerous people are having problems with the binary provided libarpack.so (in particular when julia is build with MKL (#7, #61, #62) because AFAIK libarpack.so does depend on openblas). 

BinaryProvider also fails on Gentoo with new eselect-profiles (17+) where /usr/lib is not symlinked to /usr/lib64 any more so BinaryProvider does not find OpenBlas (even if present).

I cannot imagine a reason for not using a libarpack.so already present in the system whereas there are numerous reasons for not wanting to download a prebuilt binary.

**Comment by andreasnoack** [comment]
See #5 and #7
