### ISSUE TITLE
build fails on FreeBSD-12

### ISSUE THREAD

**Issue by RobvanW** [JuliaLinearAlgebra/Arpack.jl#72]
No build on FreeBSD-12 (Arpack++ and Arpack-ng are installed in the operating system)

The  BinaryProvider has only references to  FreeBSD-11, could builds for FreeBSD-12 be added? If not, how to get the build to succeed, can this be done manually?

Below the build errors on my system:
```
              _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.4 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  FreeBSD port lang/julia10 build
|__/                   |

(v1.0) pkg> build Arpack
  Building Arpack → `~/.julia/packages/Arpack/cu5By/deps/build.log`
┌ Error: Error building `Arpack`: 
│ ERROR: LoadError: LibraryProduct(nothing, ["libarpack"], :libarpack, "Prefix(/home/rob/.julia/packages/Arpack/cu5By/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] #write_deps_file#152(::Bool, ::Function, ::String, ::Array{LibraryProduct,1}) at /home/rob/.julia/packages/BinaryProvider/TcAwt/src/Products.jl:414
│  [3] (::getfield(BinaryProvider, Symbol("#kw##write_deps_file")))(::NamedTuple{(:verbose,),Tuple{Bool}}, ::typeof(write_deps_file), ::String, ::Array{LibraryProduct,1}) at ./none:0
│  [4] top-level scope at none:0
│  [5] include at ./boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1044
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:392
│  [9] top-level scope at none:0
│ in expression starting at /home/rob/.julia/packages/Arpack/cu5By/deps/build.jl:74
└ @ Pkg.Operations /wrkdirs/usr/ports/lang/julia10/work/julia-1.0.4/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1096
```

**Comment by andreasnoack** [comment]
@ararslan Do you know the status FreeBSD-12 support? Can we add it as a target for BinaryBuilder?

**Comment by RobvanW** [comment]
FreeBSD-12.0 was released December 2018,
Julia 1.04 and 1.11 are in the pkg & ports of FreeBSD

So indeed after more than half a year of the 12.0 release I'd expect that it can safely be added as a target for BinaryBuilder.

You're right that seems to be a more general BinaryBuilder issue, that it still only supports the FreeBSD-11 target and not yet the latest release. This should thus apply to many more packages than just Arpack.

Who could initiate BinaryBuilder to start including FreeBSD-12 targets in general?

**Comment by RobvanW** [comment]
IFound the BinaryBuilder's Github page, and just left a request for adding a FreeBSD-12 target.

**Comment by ararslan** [comment]
> Do you know the status FreeBSD-12 support?

Yeah, I have a FreeBSD 12.0 partition on my desktop. I don't use it as often as I use 11.x but I've yet to run into any issues; it's been my experience that binaries built on 11.x can be used on 12.0 but the reverse is not true. When I get the chance I'll reboot into 12.0 and check the Arpack build.

In the meantime, @RobvanW, could you try using the [official Julia FreeBSD binaries](https://julialang.org/downloads) rather than the ports build?

**Comment by RobvanW** [comment]
I tested comparing the [official Julia FreeBSD binaries 1.0.4](https://julialang.org/downloads), as this corresponds to the default version that would be installed if using `pkg add julia`

Yep, installing the official FreeBSD binaries in a local folder allows building Arpack!

**Comment by ararslan** [comment]
Perfect, glad it's working for you. [As I said in the BinaryBuilder issue](https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/433#issuecomment-521015566), we always recommend people use the official Julia binaries.
