### ISSUE TITLE
error building arpack

### ISSUE THREAD

**Issue by mavogia77** [JuliaLinearAlgebra/Arpack.jl#79]
I tried to create a plot using statsplots where I encountered an error with Arpack. I tried to solve it by upgrading from Julia 1.0.3 to Julia 1.2 however the problem remains. Now when I try import Pkg; Pkg.build("Arpack") I just get a false as output

![arpack_error](https://user-images.githubusercontent.com/19654522/68543367-c0b55400-03be-11ea-9833-aaedd735ec43.png)

any ideas?

**Comment by Roger-luo** [comment]
could you show what's in your `build.log`?

**Comment by mavogia77** [comment]
what is the path to it? I looked at .julia/blogs but it isn't there

**Comment by andreasnoack** [comment]
How did you install Julia?

**Comment by Roger-luo** [comment]
@mavogia77 your error msg showed the path.

**Comment by mavogia77** [comment]
the log is empty...

I downloaded Julia from https://julialang.org/downloads/

**Comment by ViralBShah** [comment]
Can you `rm -rf .julia` and try?

**Comment by andreasnoack** [comment]
No reply so closing.
