### ISSUE TITLE
Error message if not built

### ISSUE THREAD

**Issue by matthieugomez** [JuliaLinearAlgebra/Arpack.jl#84]
Can there be a better error message if Arpack is not build?  Something like  "try ]build Arpack"

For now it gives something like `error compiling napud.... Reason:image not found`. 
Googling the error returns this issue https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/5, which is incomprehensible for mere mortals.

**Comment by andreasnoack** [comment]
Which version of Arpack are you using. I'd think that this is no longer a problem in 0.4.

**Comment by matthieugomez** [comment]
Oh awesome! The error happened yesterday so it was on a previous version of Arpack.
