### ISSUE TITLE
Have operating mode where INFO = 1 is not an error

### ISSUE THREAD

**Issue by jiahao** [JuliaLinearAlgebra/Arpack.jl#85]
I want to explicitly calculate `svds()` with a very few number of iterations; however, doing so currently throws an `ArpackException(1)`.

The documentation for `dsaupd()` says that `INFO = 1` just means that the maximum number of iterations has been reached. Arguably this should not throw an error unconditionally and the user should have access to the partial results. Manually editing `aupd_wrapper()` to turn off the exception does actually cause Arpack to emit a warning about [not having all eigenvalues converged](https://github.com/JuliaLinearAlgebra/Arpack.jl/blob/a7cdb6d7f19f076f5fadd8b58a9c5a061c48322f/src/Arpack.jl#L191)

**Comment by andreasnoack** [comment]
Maybe we can introduce the same `check=false` as we use in `cholesky`.

**Comment by jemiryguo** [comment]
i add a pullrequest to fix this [https://github.com/JuliaLinearAlgebra/Arpack.jl/pull/121](url)
