### ISSUE TITLE
Segmentation fault when using Arpack and Threads.@threads

### ISSUE THREAD

**Issue by CodeLenz** [JuliaLinearAlgebra/Arpack.jl#86]
Hi.

The following example 

```
 function test_call_parpack(NP,NM)

    # Parallel calls to Arpack
    Threads.@threads for k=1:NP

        # Generate random matrix
        A = sprand(NM,NM,0.2)

        # Call Arpack
        eigs(A)
        
    end

end
```

results in 

```
julia> test_call_parpack(1000,1000)
Segmentation fault (core dumped)

If I run the sequence 
   ```
    # Generate random matrix
        A = sprand(NM,NM,0.2)

        # Call Arpack
        eigs(A)

by hand many times, everything works fine. I suspect there must be some constraint on using external libraries in parallel, but all the variables are local to the loop and Julia just have to call multiple instances of it. Is it expected?

Julia 1.3 here
Thanks for your assistance.
```
```

**Comment by andreasnoack** [comment]
See https://stackoverflow.com/a/6972455. Arpack might not be threadsafe. Consider using a native Julia implementation such as e.g. https://github.com/haampie/ArnoldiMethod.jl

**Comment by CodeLenz** [comment]
Thanks!
